---
# consul/tasks/main.yml
# https://www.digitalocean.com/community/tutorial_series/getting-started-with-consul

- name: create configuration exists
  file:
    path: "{{ consul_etc_dir }}"
    state: directory

- name: configure
  notify: consul restart
  template:
    src: cluster.json.j2
    dest: "{{ consul_etc_dir}}/cluster.json"
    owner: consul
    group: consul
    mode: "0600"
