---
# jenkins/tasks/main.yml

- name: java required filesystems
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    - { path: /dev/fd, src: fdesc, fstype: fdescfs, opts: rw }
    - { path: /proc,   src: proc,  fstype: procfs,  opts: rw }

# From jenkins/jenkins docker image
# - name: jenkins plugins
#   copy:
#     src: "{{ item }}"
#     dest: /usr/local/bin/
#     mode: "0755"
#     owner: root
#     group: wheel
#   loop:
#     - install-plugins.sh
#     - jenkins-support

# https://github.com/jenkinsci/plugin-installation-manager-tool
- name: jenkins plugin manager
  get_url:
    url: "{{ jenkins_manager_plugin_url }}"
    dest: /root/
    mode: "0444"

- name: jenkins plugins install
  command: java -jar /root/  /usr/local/share/jenkins/jenkins.war
