---
# vault/tasks/main.yml

- name: ensure {{ vault_etc_dir }} exists
  file:
    path: "{{ vault_etc_dir }}"
    state: directory

- name: configure vault
  notify: vault restart
  template:
    src: vault.hcl.j2
    dest: "{{ vault_etc_dir}}/vault.hcl"
    owner: root
    group: "{{ root_group }}"
