---
# plays/mountain.yml

- name: mountain
  hosts: mountain
  roles:
    - name: network

    # https://wiki.freebsd.org/riscv
    # RISC-V emulator
    # - name: freebsd
    #   freebsd_packages:
    #     - opensbi
    #     - qemu        
    #     - riscv-isa-sim
    #     - screen
    #     - u-boot-qemu-riscv64

    - name: freebsd
      freebsd_service: powerd
      freebsd_rc:
        powerd_enable: "YES"
        powerd_flags: "-a hadp -b hadp -n hadp"

    - name: jailer

    - name: nfs

    - name: rsync

    - name: zfs

  tasks:
    - name: Disable root wait for USB
      lineinfile:
        regexp: "^hw.usb.no_boot_wait="
        path: /boot/loader.conf
        line: "hw.usb.no_boot_wait=1"
