base_network:
  autobridge_bridge0: tap?
  autobridge_interfaces: bridge0
  cloned_interfaces: bridge0
  ifconfig_bridge0: addm em0
  ifconfig_em0: inet 192.168.1.10 netmask 255.255.255.0
  ifconfig_em0_alias0: inet 192.168.1.18-33

base_packages:
  - bhyve-firmware
  - git-lite
  - py37-ansible
  - rsync
  - tmux

base_sysctls:
  kern.vt.enable_bell: 0
  net.link.tap.up_on_open: 1

jailer_base_snapshot: 1
jailer_dataset: zatic/jails
jailer_distsite: ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.1-RELEASE
jailer_mountpoint: /atic/jails
