---
# base_exports:
#   - /pool/atic/repo      -maproot=root -network 192.168 -mask 255.255.0.0
#   - /pool/atic/downloads -maproot=root -network 192.168 -mask 255.255.0.0

# freebsd_rc:
#   - key: mountd_flags
#     value: -r

jailer: yes
jailer_base_root: /pool/data/jail/base
jailer_base_snapshot: 5
jailer_distsite: ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.1-RELEASE
jailer_dataset: zdata/jail
jailer_directory: /pool/data/jail
jailer_interface: em0
jailer_jails:
  - name: consul11
    state: present
    ipv4: 192.168.1.201
  - name: consul12
    state: present
    ipv4: 192.168.1.202
  - name: consul13
    state: present
    ipv4: 192.168.1.203
  - name: jenkins11
    state: present
    ipv4: 192.168.1.211
  - name: monitor11
    ipv4: 192.168.1.221
    state: present

zfs_enabled: yes

zfs_datasets:
  - dataset: zdata/backup
    state: present
    properties:
      dedup: on
      compression: on
  - dataset: zdata/jail
    state: present
    properties:
      dedup: on
  - dataset: zatic/repo
    state: present
    properties:
      compression: on

zfs_pools:
  - name: zatic
    device: /dev/da0
    mountpoint: /pool/atic
  - name: zdata
    device: /dev/ada0
    mountpoint: /pool/data
