---
# roles/base/tasks/main.yml

- name: sysctl entries
  loop: "{{ base_sysctls }}"
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes

- name: install packages
  package:
    name: "{{ base_packages }}"

- name: Ensure local directories exist
  file:
    name: /usr/local/{{ item }}
    state: directory
  loop:
    - bin
    - etc

- name: hosts entries
  loop:
    - "127.0.0.1 {{ ansible_hostname }}"
  lineinfile:
    line: "{{ item }}"
    path: /etc/hosts
