---
# jailer/defaults/main.yml

jailer_base_snapshot: 0

jailer_conf: |
  allow.raw_sockets;
  
  exec.start = "/bin/sh /etc/rc";
  exec.stop  = "/bin/sh /etc/rc.shutdown jail";
  exec.clean;
  
  mount.devfs;
  
  path          = "/{{ jailer_mountpoint }}/$name";
  host.hostname = "$name";
