---
# jailer/defaults/main.yml

jails_base_snapshot: 0

jails_conf: |
  allow.raw_sockets;
  
  exec.start = "/bin/sh /etc/rc";
  exec.stop  = "/bin/sh /etc/rc.shutdown jail";
  exec.clean;
  
  mount.devfs;
  
  path          = "/{{ jails_mountpoint }}/$name";
  host.hostname = "$name";

create: "{{
    jails
    | selectattr('state', 'match', 'present')
    | list
  }}"

delete: "{{
    jails
    | selectattr('state', 'match', 'absent')
    | list
  }}"
