---
# roles/service/tasks/main.yml

- name: install {{ service }} packages
  loop: "{{ packages }}"
  package:
    name: "{{ item }}"

- name: enable {{ service }}
  service:
    name: "{{ service }}"
    enabled: yes
  notify: restart {{ service }}

- name: rc entries for {{ service }}
  with_dict: "{{ rc }}"
  lineinfile:
    regexp: "^{{ item.key }}="
    path:   "/etc/rc.conf"
    line:   "{{ item.key }}=\"{{ item.value }}\""
  notify: restart {{ service }}

- name: sysctls for {{ service }}
  with_dict: "{{ sysctls }}"
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
