---
# jenkins/tasks/main.yml

- name: java required filesystems
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    - { path: /dev/fd, src: fdesc, fstype: fdescfs, opts: rw }
    - { path: /proc,   src: proc,  fstype: procfs,  opts: rw }

# https://github.com/jenkinsci/plugin-installation-manager-tool
- name: jenkins plugin manager
  get_url:
    url: "{{ plugin_manager_url }}"
    dest: "{{ plugin_manager_path }}"

- name: jenkins plugin list file
  copy:
    src: plugins.yml
    dest: "{{ plugins_file }}"

- name: jenkins plugins install
  become: yes
  become_user: jenkins
  command: java -jar {{ plugin_manager_path }} -w {{ war_path }} -f {{ plugins_file }} -d {{ plugins_dir }}
  notify: restart jenkins
