---
# jailer/tasks/main.yml

- name: Amend service script
  patch:
    backup: yes
    src: jail.patch
    dest: /etc/rc.d/jail

- name: Create freebsd-dist
  file:
    path: /usr/freebsd-dist
    state: directory

- name: Get base distribution
  command: bsdinstall distfetch
  environment:
    BSDINSTALL_DISTSITE: "{{ jailer_distsite }}"
    BSDINSTALL_DISTDIR: /usr/freebsd-dist
    DISTRIBUTIONS: base.txz
  args:
    creates: /usr/freebsd-dist/base.txz

- name: Create base jail dataset
  zfs:
    name: "{{ jailer_dataset }}/base"
    state: present

- name: Extract base distribution
  command: tar xf /usr/freebsd-dist/base.txz -C {{ jailer_mountpoint }}/base
  args:
    creates: "{{ jailer_mountpoint }}/base/COPYRIGHT"

- name: Snapshot base jail
  zfs:
    name: "{{ jailer_dataset }}/base@{{ jailer_base_snapshot }}"
    state: present

- name: jails configuration
  blockinfile:
    path: /etc/jail.conf
    block: "{{ jailer_conf }}"
    create: yes
    owner: root
    group: wheel
    mode: "0644"
    backup: yes
    insertbefore: BOF
