---
# jailer/tasks/main.yml

- name: Amend service script
  patch:
    backup: yes
    src: jail.patch
    dest: /etc/rc.d/jail

- name: Create freebsd-dist
  file:
    path: /usr/freebsd-dist
    state: directory

- name: Get base distribution
  command: bsdinstall distfetch
  environment:
    BSDINSTALL_DISTSITE: "{{ jails_distsite }}"
    BSDINSTALL_DISTDIR: /usr/freebsd-dist
    DISTRIBUTIONS: base.txz
  args:
    creates: /usr/freebsd-dist/base.txz

- name: Create base jail dataset
  zfs:
    name: "{{ jails_dataset }}/base"
    state: present

- name: Extract base distribution
  command: tar xf /usr/freebsd-dist/base.txz -C {{ jails_mountpoint }}/base
  args:
    creates: "{{ jails_mountpoint }}/base/COPYRIGHT"

- name: Snapshot base jail
  zfs:
    name: "{{ jails_dataset }}/base@{{ jails_base_snapshot }}"
    state: present

- name: Create jail configuration file
  blockinfile:
    path: /etc/jail.conf
    block: "{{ jails_conf }}"
    create: yes
    owner: root
    group: wheel
    mode: "0644"
    backup: yes
    insertbefore: BOF
  register: jails_restart
  notify: jails restart

- name: Create jails
  include_tasks: create.yml

- name: Delete jails
  include_tasks: delete.yml
